i get this error on build this app locally on docker containers "2.141    ▲ Next.js 15.2.3 2.141    - Environments: .env 2.143 2.279    Creating an optimized production build ... 57.11  ✓ Compiled successfully 57.13    Skipping validation of types 57.13    Skipping linting 57.65    Collecting page data ... 64.90    Generating static pages (0/6) ... 67.09  ⨯ useSearchParams() should be wrapped in a suspense boundary at page "/". Read more: https://nextjs.org/docs/messages/missing-suspense-with-csr-bailout 67.09     at a (/app/.next/server/chunks/169.js:3:11414) 67.09     at f (/app/.next/server/chunks/169.js:5:28649) 67.09     at s$ (/app/.next/server/app/page.js:5:2995) 67.09     at nL (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:46773) 67.09     at nF (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:48548) 67.09     at nq (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:67434) 67.09     at nH (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:65009) 67.09     at nU (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:47125) 67.09     at nF (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:48594) 67.09     at nF (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:64360) 67.09 Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error 67.09 Export encountered an error on /page: /, exiting the build. 67.09  ⨯ Next.js build worker exited with code: 1 and signal: null ------
 1 warning found (use docker --debug to expand):
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 31)
Dockerfile:25
--------------------
  23 |
  24 |     # Build the Next.js application for production
  25 | >>> RUN npm run build
  26 |
  27 |     # Expose the port the app runs on (default is 3000)
--------------------
ERROR: failed to solve: process "/bin/sh -c npm run build" did not complete successfully: exit code: 1
"